spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/model  #docker container inspect nejake_cislo a tam hledat gateway
    username: admin
    password: admin
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
