spring:
  datasource:
    url: jdbc:h2:mem:ecb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    url: jdbc:h2:file:/data/demo
    username: ecb
    password: bce
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /console
  liquibase:
    enabled: true
